# Подтягиваем всё из основного файла, меняем только пути и хосты
server.port=3333
grpc.server.port=6565

# Пути, адаптированные под файловую систему Linux внутри контейнера
shotsPath=shots/
mongoPrepareShotsPath=mongoPrepareShots/

# Внутри Docker-сети базы данных доступны по именам контейнеров, а не localhost!
eureka.client.serviceUrl.defaultZone=http://eureka-server:1111/eureka/
spring.data.mongodb.uri=mongodb://mongodb:27017/game

eureka.client.instance.leaseRenewalIntervalInSeconds=5
eureka.client.jersey.enabled=false
eureka.instance.prefer-ip-address=true
management.endpoints.web.exposure.include=*
spring.cache.type=caffeine
spring.cache.cache-names=items_list
spring.cache.caffeine.spec=maximumSize=1000,expireAfterWrite=15m
spring.threads.virtual.enabled=true
eureka.instance.metadata-map.grpc.port=${grpc.server.port}
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%30.30thread] %logger{36} - %msg%n
