# Spring properties
spring.application.name=mongo-service

# HTTP Server
server.port=3333

eureka.client.serviceUrl.defaultZone=http://localhost:1111/eureka/
eureka.client.instance.leaseRenewalIntervalInSeconds=5
eureka.client.jersey.enabled=false

# Чтобы Eureka регистрировала IP, а не странные хосты типа host.docker.internal
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=*

mongodbPath=C:\\mongodb\\bin\\mongod.exe
shotsPath=\\src\\main\\resources\\static\\shots\\
mongoPrepareShotsPath=\\src\\main\\resources\\static\\mongoPrepareShots\\
mongoUri=mongodb://localhost

spring.data.mongodb.uri=mongodb://localhost:27017/shopDB

# Включаем поддержку Caffeine
spring.cache.type=caffeine
spring.cache.cache-names=items_list,categories
spring.cache.caffeine.spec=maximumSize=1000,expireAfterWrite=15m

spring.threads.virtual.enabled=true

# Правильный ключ для порта
grpc.server.port=6565

# Включаем отправку данных о gRPC в Eureka
eureka.instance.metadata-map.grpc.port=${grpc.server.port}


