# Имя приложения для регистрации в реестре Eureka
spring.application.name=mongo-service

# Порты микросервиса (HTTP REST и gRPC)
server.port=3333
grpc.server.port=6565

# Настройки интеграции с Eureka Server внутри Docker-сети
eureka.client.serviceUrl.defaultZone=http://eureka-server:1111/eureka/
eureka.client.instance.leaseRenewalIntervalInSeconds=5
eureka.client.jersey.enabled=false
eureka.instance.prefer-ip-address=true
eureka.instance.metadata-map.grpc.port=${grpc.server.port}

# Подключение к СУБД MongoDB по имени контейнера
spring.data.mongodb.uri=mongodb://mongodb:27017/game

# Относительные Linux-пути для сохранения и чтения картинок внутри /app/
shotsPath=shots/
mongoPrepareShotsPath=mongoPrepareShots/

# Включаем поддержку Caffeine-кэша
spring.cache.type=caffeine
spring.cache.cache-names=items_list
spring.cache.caffeine.spec=maximumSize=1000,expireAfterWrite=15m

# Включаем виртуальные потоки (Project Loom)
spring.threads.virtual.enabled=true

# Настройки логирования и отображения потоков
management.endpoints.web.exposure.include=*
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%30.30thread] %logger{36} - %msg%n
